### ISSUE TITLE
MaxMind.Db 2.1.1 Strong name signature could not be verified

### ISSUE THREAD

**Issue by jmojiwat** [maxmind/MaxMind-DB-Reader-dotnet#31] opened 2016-08-07 18:27 UTC
After updating to MaxMind.GeoIP2 2.7 and MaxMind.Db 2.1.1 in my ASP.NET MVC 5 application, I get the following error:

Could not load file or assembly MaxMind.Db' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key

The error went away when I downgraded to MaxMind.GeoIP2 2.6 and MaxMind.Db 2.0.0.

**Comment by deathgore** [comment] 2016-08-08 10:13
+1

**Comment by oschwald** [comment] 2016-08-08 13:54
Thanks for reporting this. I haven't been able to reproduce it with .NET Core builds, but I'll try it with a standard .NET 4.6 build in VS. Are the assemblies you are generating signed themselves or does this happen when generating unsigned assemblies as well?

**Comment by deathgore** [comment] 2016-08-08 14:15
I have it on .net 4.6 for unsigned assemblies.

**Comment by oschwald** [comment] 2016-08-08 14:25
I just tried creating a new .NET 4.5 project in VS 2015. The resulting assembly works regardless of whether it is signed or not. Does this only happen in your existing project or does it happen in new projects too? If you can reproduce this in a new project, would it be possible for you to send me the test project with the issue?

**Comment by deathgore** [comment] 2016-08-08 14:42
You're right, normal build works. For me fails asp net compiler.

I attached an empty WebProject with a publish  profile to file system -> c:\temp\1 

1. Open the solution
2. Nuget restore
3. Right click on project Publish

 Fails with:
ASPNETCOMPILER(0,0): Error ASPCONFIG: Could not load file or assembly 'MaxMind.Db, Version=2.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

[WebApplication4.zip](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/files/407032/WebApplication4.zip)

**Comment by oschwald** [comment] 2016-08-08 15:23
Thanks! I am able to reproduce it with your project.

**Comment by oschwald** [comment] 2016-08-08 17:03
This should be fixed. The underlying cause seems to be that the bad release was done on Linux and the .NET Core CLI tools did not properly sign the binaries there. I believe this is related to https://github.com/dotnet/cli/issues/3073

**Closed by oschwald** 2016-08-08 17:03 UTC
